target("pandagl")
    set_kind("$(kind)")
    add_files("src/*.c")
    add_headerfiles("include/pandagl.h")
    add_headerfiles("include/(pandagl/*.h)")
    add_deps("yutil", "lcui-def")

target("pandagl_tests")
    set_kind("binary")
    add_files("test/*.c")
    add_deps("ctest", "pandagl")
