import { Text, Widget } from "@lcui/react";
import CodeBlockCopy from "../../../components/code-block-copy";

export default function QuickStartDocPage() {
  return (
    <Widget className="doc-page">
      <h1>Quick Start</h1>
      <p className="doc-page-desc">{`Get up and running with LCUI in minutes.`}</p>
      <Widget className="doc-section">
        <h2>Prerequisites</h2>
        <ul>
          <li><Text>{`[b]Operating system[/b] — Windows (recommended) or Linux`}</Text></li>
          <li><Text>{`[b]Node.js[/b] — Required to run [bgcolor=#eee] @lcui/cli [/bgcolor]`}</Text></li>
          <li><Text>{`[b]xmake[/b] — C/C++ build tool`}</Text></li>
          <li><Text>{`[b]Git[/b] — Download and manage source code`}</Text></li>
        </ul>
      </Widget>
      <Widget className="doc-section">
        <h2>Installation</h2>
        <p>{`Install the LCUI CLI globally:`}</p>
        <Widget className="code-block" data-language="sh" data-source="en/overview/quick-start/0">
          <Widget className="code-block-header">
            <Text className="code-block-title">Shell</Text>
          </Widget>
          <Widget className="code-block-body">
            <CodeBlockCopy />
            <Text className="code-line">{`npm install -g @lcui/cli`}</Text>
          </Widget>
        </Widget>
        <p>{`Create and run your first app:`}</p>
        <Widget className="code-block" data-language="sh" data-source="en/overview/quick-start/1">
          <Widget className="code-block-header">
            <Text className="code-block-title">Shell</Text>
          </Widget>
          <Widget className="code-block-body">
            <CodeBlockCopy />
            <Text className="code-line">{`lcui create my-app`}</Text>
            <Text className="code-line">{`[color=#953800]cd[/color] my-app`}</Text>
            <Text className="code-line">{`lcui build`}</Text>
            <Text className="code-line">{`xmake run app`}</Text>
          </Widget>
        </Widget>
        <p>{`[bgcolor=#eee] lcui create [/bgcolor] clones a minimal project from the lcui-quick-start template repository, including xmake.lua configuration, example code, and dependencies. Once done, run [bgcolor=#eee] lcui build [/bgcolor] to compile TSX resources, then [bgcolor=#eee] xmake run app [/bgcolor] to launch the application.`}</p>
      </Widget>
      <Widget className="doc-section">
        <h2>Next steps</h2>
        <ul>
          <li><Text>{`Explore the sample project generated by [bgcolor=#eee] lcui create [/bgcolor] — look at the code and file structure to understand the basics of an LCUI application.`}</Text></li>
          <li><Text>{`Read the widget reference (Button, Text, TextInput, Anchor, ScrollArea) to learn about built-in widgets.`}</Text></li>
          <li><Text>{`Read the Styling chapter to learn how to apply CSS properties to widgets.`}</Text></li>
          <li><Text>{`Read the Customization chapter to learn how to create custom widgets.`}</Text></li>
          <li><Text>{`Read the TSX & Dev Tools chapter to understand [bgcolor=#eee] @lcui/react [/bgcolor] usage and limitations in depth.`}</Text></li>
        </ul>
      </Widget>
      <Widget className="doc-section">
        <h2>Having trouble?</h2>
        <p>{`If you run into problems while learning, you can get help through:`}</p>
        <ul>
          <li><Text>{`Ask questions on GitHub Discussions (use the [bgcolor=#eee] Q&A [/bgcolor] label).`}</Text></li>
          <li><Text>{`Check CONTRIBUTING.md in the repository root to learn how to contribute.`}</Text></li>
        </ul>
      </Widget>
    </Widget>
  );
}
