target("lcui-tests")
    set_default(false)
    set_kind("binary")
    set_group("tests")
    set_rundir("fixtures")
    add_includedirs("helpers")
    add_files("main.c", "integration/*.c", "scenes/*.c")
    add_deps("lcui", "ctest")
    add_rules("tests.runnable")
    add_tests("default", {group = "tests"})

includes("previews/xmake.lua")
