target("ctest-tests")
    set_default(false)
    set_kind("binary")
    set_group("tests")
    set_rundir(".")
    add_files("test_str.c", "test_grep.c", "main.c")
    add_deps("ctest", "yutil")
    add_rules("tests.runnable")
    add_tests("default", {group = "tests"})
