/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{tsx,html}"],
  theme: {
    extend: {},
  },
  corePlugins: [
    "display",
    "flexDirection",
    "flex",
    "flexShrink",
    "flexGrow",
    "alignItems",
    "justifyContent",
    "width",
    "height",
    "minWidth",
    "minHeight",
    "maxWidth",
    "maxHeight",
    "overflow",
    "padding",
    "margin",
    "gap",
    "borderRadius",
    "borderWidth",
    "borderColor",
    "backgroundColor",
    "textColor",
    "fontFamily",
    "fontSize",
    "fontWeight",
    "lineHeight",
    "opacity",
    "whitespace",
    "cursor",
  ],
};
