target("doc-viewer")
    set_default(false)
    set_group("lcui-examples")
    set_prefixdir("doc-viewer", {bindir = "."})
    set_kind("binary")
    set_rundir("dist")
    add_deps("lcui")
    add_files("app/**.c")
    add_installfiles("dist/(assets/*)")
    set_warnings("all")
