target("todolist")
    set_default(false)
    set_group("lcui-examples")
    set_prefixdir("todolist", {bindir = "."})
    set_kind("binary")
    set_rundir("app")
    add_deps("lcui")
    add_files("src/*.c")
    add_installfiles("app/*")
